const acts = {
  GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',

  POST_TODO_REQUEST: 'POST_TODO_REQUEST',
  POST_TODO_SUCCESS: 'POST_TODO_SUCCESS',

  PUT_TODO_REQUEST: 'PUT_TODO_REQUEST',
  PUT_TODO_SUCCESS: 'PUT_TODO_SUCCESS',

  DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',

  ADD_ERROR: 'ADD_ERROR',
  NO_ERROR: 'NO_ERROR',
}

export default acts